export const sections = [
  {
    title: "section 1 - elemental harmony",
    subsections: [
      { title: "honesty vs deception", range: [1, 6] },
      { title: "loyalty vs independence", range: [7, 12] },
      { title: "kindness vs self-preservation", range: [13, 18] },
      { title: "laughter vs cynicism", range: [19, 24] },
      { title: "generosity vs self-interest", range: [25, 30] },
      { title: "work ethic vs convenience", range: [31, 42] },
      { title: "empathy vs detachment", range: [43, 50] },
      { title: "sharing vs withholding", range: [51, 60] },
      { title: "fairness vs self-interest", range: [61, 80] },
    ],
    questionCount: 80,
  },
  {
    title: "section 2 - temperament & energy signature",
    subsections: [
      { title: "extraversion vs introversion basics", range: [81, 86] },
      { title: "social engagement vs withdrawal", range: [87, 92] },
      { title: "structure vs flexibility", range: [93, 98] },
      { title: "routine vs spontaneity", range: [99, 104] },
      { title: "energy sources vs drains", range: [105, 110] },
      { title: "group dynamics vs solitude", range: [111, 120] },
      { title: "adaptability vs stability", range: [121, 130] },
      { title: "interaction preferences vs avoidance", range: [131, 140] },
      { title: "recharge methods vs exhaustion", range: [141, 150] },
    ],
    questionCount: 70,
  },
  {
    title: "section 3 - cognitive style",
    subsections: [
      { title: "analytical vs intuitive / perfectionist vs pragmatic", range: [151, 160] },
      { title: "traditionalist vs progressive/revolutionary", range: [161, 170] },
      { title: "logic vs intuition extension", range: [171, 180] },
      { title: "planning vs improvisation", range: [181, 190] },
      { title: "detail vs big picture", range: [191, 200] },
      { title: "evidence vs instinct", range: [201, 210] },
      { title: "systematic vs creative", range: [211, 220] },
      { title: "convention vs innovation", range: [221, 230] },
    ],
    questionCount: 80,
  },
  {
    title: "section 4 - attachment & relational patterns",
    subsections: [
      { title: "anxious-preoccupied / avoidant-dismissive attachments", range: [231, 240] },
      { title: "secure attachments / protector-caretaker roles", range: [241, 250] },
      { title: "emotional bonds vs distance", range: [251, 260] },
      { title: "support vs independence", range: [261, 270] },
      { title: "forgiveness vs grudges", range: [271, 280] },
      { title: "trust vs suspicion", range: [281, 300] },
    ],
    questionCount: 70,
  },
  {
    title: "section 5 - niche interests & aesthetic preferences",
    subsections: [],
    questionCount: 70,
  },
  {
    title: "section 6 - crisis response archetypes / moral frameworks",
    subsections: [
      { title: "fight / flight / freeze / fawn / delegation vs solo-hero", range: [371, 380] },
      { title: "moral absolutist vs moral relativist", range: [381, 390] },
      { title: "risk assessment vs impulsivity", range: [391, 400] },
      { title: "calm vs panic", range: [401, 410] },
      { title: "preparation vs reaction", range: [411, 420] },
      { title: "collaboration vs independence", range: [421, 430] },
      { title: "recovery vs dwell", range: [431, 440] },
      { title: "ethics in crisis vs pragmatism", range: [441, 450] },
    ],
    questionCount: 80,
  },
  {
    title: "section 7 - relationships, self-perception, & existential growth",
    subsections: [],
    questionCount: 78,
  },
]

export const questions: string[] = [
  // section 1 - elemental harmony (1-80)
  "i would rather hurt someone with the truth than comfort them with a lie.",
  "white lies are harmless if they prevent unnecessary pain.",
  "brutal honesty without tact is just cruelty.",
  "even close friends don't get to know everything about me.",
  "secrets are burdens; i feel better when everything is out in the open.",
  "some truths are better left buried forever.",
  "once i commit to someone or something, nothing can make me abandon it.",
  "loyalty that blinds you to someone's faults is dangerous.",
  "i would betray a principle before i'd betray a friend.",
  "if a friend repeatedly hurts others, i'll eventually cut ties.",
  "i stay loyal even when the person doesn't deserve it.",
  "my independence is more important than any relationship.",
  "i feel physical pain when i see someone else suffering.",
  "i help others only when it's convenient.",
  "saying 'no' to someone in need makes me feel guilty for days.",
  "kindness without boundaries is self-destruction.",
  "i secretly enjoy watching arrogant people fail.",
  "i will put myself in danger to protect a stranger.",
  "life without laughter is meaningless.",
  "i laugh at things others find disturbing or offensive.",
  "serious topics should be treated seriously; jokes cheapen them.",
  "i use humour to hide pain i don't want others to see.",
  "making others laugh is the best feeling in the world.",
  "too much laughter feels hollow if there's no substance behind it.",
  "i give until it hurts, then keep giving.",
  "people who don't give back don't deserve my time.",
  "i love giving gifts more than receiving them.",
  "i keep score subconsciously of what i give vs what i get.",
  "extravagant gestures are the truest form of love.",
  "i resent people who only call when they need something.",
  "i take pride in manual labour or gardening.",
  "i prefer to fix things myself rather than hire help.",
  "i value family gatherings and traditions.",
  "i avoid shortcuts in my work or projects.",
  "i have a signature accessory i wear often.",
  "i participate in local competitions or events for fun.",
  "i prepare homemade food from basic ingredients.",
  "i hold firm to my personal principles.",
  "i assist neighbours without expecting return favours.",
  "i enjoy listening to folk or country music.",
  "i prioritise honesty in all my interactions.",
  "i favour practical work over formal social events.",
  "i feel compelled to offer support to those in distress.",
  "i offer aid to strangers without expectation.",
  "i experience empathy for animals in pain.",
  "i volunteer time to help the vulnerable.",
  "i find it difficult to ignore pleas for help.",
  "i place others' wellbeing above my comfort.",
  "i feel satisfied when alleviating suffering.",
  "i provide comfort to those feeling low.",
  "i share resources with those less fortunate.",
  "i donate items to charity regularly.",
  "i offer my time to community causes.",
  "i lend a hand to friends in need.",
  "i give compliments to boost confidence.",
  "i share knowledge to assist others.",
  "i provide emotional support during hard times.",
  "i offer advice when asked.",
  "i help organise events for good causes.",
  "i contribute to group efforts selflessly.",
  "i seek to understand others' perspectives before judging.",
  "i forgive mistakes in friends easily.",
  "i maintain long-term connections despite distance.",
  "i express gratitude for small acts.",
  "i prioritise harmony in groups.",
  "i avoid gossip to protect reputations.",
  "i celebrate diversity in viewpoints.",
  "i listen without interrupting.",
  "i encourage open communication.",
  "i respect boundaries in relationships.",
  "i build trust through reliability.",
  "i offer help without being asked.",
  "i value kindness in daily interactions.",
  "i seek peaceful resolutions to conflicts.",
  "i show patience with others' flaws.",
  "i appreciate acts of generosity.",
  "i promote fairness in dealings.",
  "i support those facing hardship.",
  "i practise empathy in conversations.",
  "i foster positive environments.",

  // section 2 - temperament & energy signature (81-150)
  "i'm the first to arrive and the last to leave any social event.",
  "large crowds energise me more than they exhaust me.",
  "i love being the centre of attention and performing.",
  "i get overstimulated easily and need quiet recharge time.",
  "one-on-one conversations are deeper and more satisfying than group chats.",
  "i feel lonely in a room full of people if i'm not truly connecting.",
  "silence in a group makes me uncomfortable; i fill it.",
  "i prefer observing a party from the edges rather than diving in.",
  "people say i 'light up the room' when i walk in.",
  "i'm perfectly happy spending an entire weekend completely alone.",
  "i need a lot of structure and routine to function at my best.",
  "strict schedules make me feel trapped.",
  "i make detailed to-do lists and feel accomplished crossing things off.",
  "plans are made to be broken; flexibility is freedom.",
  "i hate surprises unless i'm the one giving them.",
  "surprises are the spice of life.",
  "i organise other people's lives as much as (or more than) my own.",
  "too much order feels suffocating and soul-crushing.",
  "chaos and randomness recharge my creativity.",
  "i secretly crave chaos when life gets too predictable.",
  "i organise unexpected gatherings for no special reason.",
  "i recover from difficulties with optimism.",
  "i gather miscellaneous items for potential creative uses.",
  "i create impromptu songs or rhymes to lift moods.",
  "i notice when someone could use encouragement.",
  "i use light-hearted tricks to surprise people.",
  "i remember details like preferred tastes or hobbies.",
  "i move spontaneously to express joy.",
  "i welcome newcomers with enthusiasm.",
  "i keep supplies ready for sudden events.",
  "i distribute small tokens to brighten days.",
  "i find humour in unsettling situations.",
  "i initiate group activities frequently.",
  "i thrive in dynamic environments.",
  "i adapt quickly to unexpected changes.",
  "i enjoy mixing up routine days.",
  "i experiment with new ideas often.",
  "i seek variety in daily tasks.",
  "i improvise solutions on the spot.",
  "i prefer flexible plans over rigid ones.",
  "i feel energised by spontaneous outings.",
  "i create fun from ordinary moments.",
  "i surprise others with thoughtful acts.",
  "i laugh off minor setbacks.",
  "i join social events eagerly.",
  "i maintain high energy in groups.",
  "i start conversations with strangers.",
  "i host casual meetups.",
  "i share stories to entertain.",
  "i celebrate small victories loudly.",
  "i prefer quiet evenings to loud parties.",
  "i recharge alone after social interactions.",
  "i observe before participating in groups.",
  "i value deep connections over many acquaintances.",
  "i avoid large gatherings when possible.",
  "i enjoy solitary hobbies.",
  "i reflect in silence regularly.",
  "i prefer reading to talking.",
  "i listen more than i speak.",
  "i find peace in solitude.",
  "i avoid unnecessary social obligations.",
  "i appreciate personal space.",
  "i process thoughts internally.",
  "i enjoy independent activities.",
  "i seek calm environments.",
  "i value introspection.",
  "i prefer small circles.",
  "i avoid spotlight situations.",
  "i recharge through quiet time.",
  "i find comfort in routine solitude.",

  // section 3 - cognitive style (151-230)
  "i overthink every decision until it's perfect.",
  "i trust my gut even when logic says otherwise.",
  "data, research, and evidence are the only way to be sure.",
  "some things can't be explained by science or logic.",
  "i'm a perfectionist who will redo something ten times to get it right.",
  "'good enough' is usually good enough.",
  "i notice tiny details others completely miss.",
  "i'm always thinking ten steps ahead.",
  "i live in the moment and worry about consequences later.",
  "i replay past conversations in my head analysing what i could have said better.",
  "tradition and 'the way things have always been done' are important.",
  "old rules should be challenged or thrown out if they no longer serve us.",
  "i admire rebels and revolutionaries.",
  "authority figures usually know what they're doing and should be respected.",
  "power corrupts almost everyone eventually.",
  "with great power comes great responsibility - i'd handle it well.",
  "i'd rather lead than follow, even if i'm not sure where i'm going.",
  "following a competent leader is smarter than going it alone.",
  "breaking rules is fine if nobody gets hurt.",
  "some rules are worth breaking for a higher moral purpose.",
  "i prioritise acquiring new skills over social activities.",
  "i feel uneasy if my workspace is cluttered.",
  "i stay up late studying advanced subjects.",
  "i use checklists for routine tasks to maintain efficiency.",
  "i favour intellectual exchanges over casual talk.",
  "i consult experts for advice on challenging issues.",
  "i maintain a record of my daily insights.",
  "i base decisions on evidence rather than emotions.",
  "i engage in philosophical discussions.",
  "i aim for expertise in my chosen fields.",
  "i imagine efficient ways to navigate daily routines.",
  "i conduct experiments to test ideas.",
  "i seek logical explanations for events.",
  "i organise information systematically.",
  "i analyse problems from multiple angles.",
  "i prefer evidence-based approaches.",
  "i update my knowledge regularly.",
  "i question assumptions in arguments.",
  "i use data to support my views.",
  "i plan projects with contingencies.",
  "i enjoy solving puzzles.",
  "i read extensively on various topics.",
  "i apply theory to practical situations.",
  "i value precision in communication.",
  "i explore concepts in depth.",
  "i document processes for future reference.",
  "i adapt strategies based on feedback.",
  "i test hypotheses in everyday life.",
  "i seek patterns in data.",
  "i collaborate on intellectual projects.",
  "i review past decisions for improvement.",
  "i use tools to enhance productivity.",
  "i balance theory and practice.",
  "i pursue continuous learning.",
  "i organise thoughts logically.",
  "i evaluate options carefully.",
  "i integrate new information quickly.",
  "i prioritise accuracy over speed.",
  "i challenge conventional wisdom.",
  "i refine ideas through iteration.",
  "i question established norms.",
  "i seek innovative solutions.",
  "i admire creative thinkers.",
  "i experiment with new methods.",
  "i adapt to changing circumstances.",
  "i value originality in ideas.",
  "i explore alternative viewpoints.",
  "i promote progress in my field.",
  "i challenge status quo.",
  "i embrace new technologies.",
  "i foster inventive approaches.",
  "i pursue unconventional paths.",
  "i encourage reform in systems.",
  "i support change for improvement.",
  "i critique outdated practices.",
  "i innovate in daily tasks.",
  "i seek better ways to do things.",
  "i value forward-thinking.",
  "i adapt traditions to modern times.",
  "i advocate for evolution in ideas.",

  // section 4 - attachment & relational patterns (231-300)
  "i worry that people will stop liking me if i'm not useful to them.",
  "i push people away before they have the chance to leave me.",
  "i test my friends' loyalty, sometimes unconsciously.",
  "i assume relationships will end, so i keep emotional distance.",
  "when i care about someone, i care intensely and forever.",
  "i'm terrified of being abandoned or replaced.",
  "i feel responsible for other people's emotions.",
  "i apologise even when something clearly isn't my fault.",
  "i have a hard time saying 'no' to anyone.",
  "deep down, i believe i'm not worthy of love unless i earn it.",
  "i'm the one friends call when they need practical help or protection.",
  "taking care of others gives my life meaning.",
  "i secretly enjoy when people depend on me.",
  "i adopt 'little siblings' or mentor figures naturally.",
  "i'm overprotective; i'd rather get hurt myself than see my loved ones suffer.",
  "people say i act like the group's mom/dad.",
  "i hide my own pain so i don't burden others.",
  "i'd sacrifice my dreams to keep my family/friends happy.",
  "i feel guilty when i put my own needs first.",
  "quiet acts of service are my primary love language.",
  "i listen attentively to understand others' needs.",
  "i participate in community support activities.",
  "i prefer small gatherings with close friends.",
  "i resolve disagreements calmly.",
  "i care for those in need until they recover.",
  "i show frustration only when repeatedly provoked.",
  "i relax during quiet walks in nature.",
  "i observe wildlife in the morning.",
  "i offer guidance to younger people.",
  "i protect loved ones from harm.",
  "i provide stability in relationships.",
  "i nurture friendships with care.",
  "i share burdens with others.",
  "i prioritise group harmony.",
  "i console friends in distress.",
  "i maintain long-term connections.",
  "i celebrate others' successes.",
  "i forgive easily to preserve bonds.",
  "i invest time in relationships.",
  "i express appreciation regularly.",
  "i build trust through consistency.",
  "i avoid conflicts to keep peace.",
  "i support dreams of those close to me.",
  "i create safe spaces for sharing.",
  "i remember important dates.",
  "i offer comfort in tough times.",
  "i value mutual respect in ties.",
  "i encourage personal growth in others.",
  "i form bonds based on shared values.",
  "i seek balance in giving and receiving.",
  "i maintain contact with distant friends.",
  "i resolve misunderstandings promptly.",
  "i show affection through actions.",
  "i value honesty in relationships.",
  "i listen to concerns without judgment.",
  "i celebrate anniversaries.",
  "i offer help during stressful times.",
  "i respect personal space.",
  "i share joys and sorrows.",
  "i foster mutual support.",
  "i avoid manipulation in interactions.",
  "i promote equality in partnerships.",
  "i express love openly.",
  "i seek compromise in disagreements.",
  "i appreciate small gestures.",
  "i build networks through kindness.",
  "i maintain positive attitudes.",
  "i encourage independence in others.",
  "i value loyalty above all.",
  "i create lasting memories with loved ones.",

  // section 5 - niche interests & aesthetic preferences (301-370)
  "i carry guilt for years over mistakes i've made.",
  "i feel shame about who i am at my core, not just what i've done.",
  "i sometimes want to control every variable in a situation.",
  "losing control terrifies me more than anything.",
  "when i'm angry, i become someone i don't recognise.",
  "i've hurt people in the past and still beat myself up over it.",
  "part of me enjoys having power over others.",
  "i fear that if people saw the real me, they'd hate me.",
  "i'm capable of genuine, profound change if i choose it.",
  "everyone deserves a second chance, no matter how bad they were.",
  "fashion and personal style are forms of art and self-expression.",
  "i spend hours coordinating outfits and accessories.",
  "music is my escape; i can't live without my headphones.",
  "extreme sports or high-speed anything gives me life.",
  "being surrounded by animals instantly calms me.",
  "i lose track of time in bookstores or libraries.",
  "magic, the occult, or esoteric knowledge fascinates me.",
  "i love the spotlight and performing on stage.",
  "geology, rocks, or collecting shiny things is weirdly soothing.",
  "i'm drawn to the ocean or sky - wide open spaces.",
  "i sketch ideas in my free time.",
  "i follow trends in design or style.",
  "i help others update their appearance.",
  "i gather unique materials for projects.",
  "i use refined language in conversation.",
  "i react dramatically to surprises.",
  "i manage creative ventures.",
  "i draw inspiration from natural elements.",
  "i focus on grace in daily actions.",
  "i create handmade items as presents.",
  "i offer constructive feedback on appearances.",
  "i aspire to sophisticated social circles.",
  "i consider appearance as key as content.",
  "i share my work freely with friends.",
  "i plan outfits for important occasions.",
  "i collect vintage items.",
  "i appreciate minimalist design.",
  "i experiment with hairstyles.",
  "i attend art exhibitions.",
  "i mix patterns in outfits.",
  "i prefer handmade over mass-produced.",
  "i seek unique accessories.",
  "i follow sustainable fashion.",
  "i customise clothing.",
  "i enjoy window shopping.",
  "i coordinate colours carefully.",
  "i value quality over quantity in wardrobe.",
  "i repair garments myself.",
  "i admire classic styles.",
  "i express personality through attire.",
  "i collect stamps or coins.",
  "i enjoy photography as a hobby.",
  "i practice yoga for relaxation.",
  "i explore hiking trails.",
  "i read science fiction novels.",
  "i watch documentaries regularly.",
  "i paint or draw in spare time.",
  "i play musical instruments.",
  "i garden for pleasure.",
  "i cook experimental dishes.",
  "i build models or crafts.",
  "i write poetry or stories.",
  "i attend live theatre.",
  "i participate in book clubs.",
  "i learn languages for fun.",
  "i study history extensively.",
  "i practice meditation.",
  "i engage in stargazing.",
  "i collect rare books.",
  "i attend cultural festivals.",

  // section 6 - crisis response archetypes / moral frameworks (371-450)
  "in a crisis i charge straight at the problem.",
  "in a crisis i freeze and need time to process.",
  "in a crisis i run or look for the nearest exit.",
  "in a crisis i try to make everyone feel better first.",
  "i take charge immediately and start giving orders.",
  "i work best alone when the stakes are high.",
  "i delegate tasks like a general during emergencies.",
  "i crack jokes to lighten the mood in danger.",
  "i analyse the situation for ten minutes before acting.",
  "my plans have plans - contingency on top of contingency.",
  "there is objective good and evil in the world.",
  "morality depends on context; almost nothing is black-and-white.",
  "some people are just born evil and can't be saved.",
  "every villain is a hero in their own story.",
  "forgiveness without consequences is meaningless.",
  "true redemption requires visible, long-term change.",
  "i'd rather be feared than loved if i had to choose.",
  "love and friendship can fix literally anything.",
  "power should be taken, not waited for.",
  "the ends justify the means if the cause is noble.",
  "i challenge myself to improve performance constantly.",
  "i dislike failure intensely.",
  "i support others against unfair odds.",
  "i collect items from admired figures or groups.",
  "i seek thrills from high-energy activities.",
  "i share accomplishments without excess pride.",
  "i build resilience through difficult conditions.",
  "i motivate others to exceed their limits.",
  "i imagine achieving extraordinary feats.",
  "i value quick action over careful planning.",
  "i engage in physical challenges regularly.",
  "i recover from crises swiftly.",
  "i assess risks before acting.",
  "i rally groups during emergencies.",
  "i remain calm under pressure.",
  "i prioritise safety in chaotic situations.",
  "i improvise solutions in stress.",
  "i seek help when overwhelmed.",
  "i reflect on past crises for lessons.",
  "i prepare emergency kits.",
  "i communicate clearly in turmoil.",
  "i follow protocols in danger.",
  "i adapt to unexpected threats.",
  "i protect vulnerable people first.",
  "i use humour to ease tension.",
  "i evaluate options rapidly.",
  "i coordinate efforts efficiently.",
  "i avoid panic in groups.",
  "i learn from failure experiences.",
  "i maintain composure in adversity.",
  "i develop contingency strategies.",
  "i collaborate in high-stakes scenarios.",
  "i focus on immediate needs.",
  "i debrief after events.",
  "i train for potential risks.",
  "i support recovery after crises.",
  "i identify early warning signs.",
  "i balance caution and action.",
  "i document incident details.",
  "i seek feedback on handling.",
  "i practise emergency drills.",
  "i stay vigilant in uncertain times.",
  "i encourage team preparedness.",
  "i use resources wisely in emergencies.",
  "i maintain focus during chaos.",
  "i assist in post-crisis cleanup.",
  "i learn safety techniques.",
  "i share crisis stories for learning.",
  "i build emergency networks.",
  "i prioritise mental resilience.",
  "i review safety procedures.",
  "i promote calm in teams.",
  "i adapt plans on the fly.",
  "i seek professional training.",
  "i value crisis experience.",
  "i support emotional recovery.",
  "i prepare for natural disasters.",
  "i communicate risks effectively.",
  "i foster resilience in others.",
  "i reflect on ethical decisions in crises.",

  // section 7 - relationships, self-perception, & existential growth (451-528)
  "i fall in love hard and fast; crushes hit me like lightning.",
  "i'm extremely picky and rarely develop romantic feelings.",
  "flirting is a fun game, even if i'm not serious.",
  "i get jealous easily if my partner even looks at someone else.",
  "i'm happiest in a big, loud found-family environment.",
  "i form intense one-on-one bonds and don't need a big circle.",
  "physical touch is my primary way of showing affection.",
  "i'd rather write a ten-page letter than say 'i love you' out loud.",
  "i'm terrified of vulnerability in romance.",
  "i secretly want someone to take care of me for once.",
  "i'm reliable - if i say i'll do something, it gets done.",
  "i'm the wildcard nobody can predict.",
  "people come to me when they need an answer or solution.",
  "i'm the emotional support of my friend group.",
  "i'm the fashion police and aesthetic judge.",
  "i'm the adrenaline junkie who drags everyone on adventures.",
  "i'm the quiet one who notices everything.",
  "i'm the comic relief, even at my own expense.",
  "i work myself to exhaustion for the people i love.",
  "i sometimes feel like i don't quite belong anywhere.",
  "i admire elegance and high society.",
  "i'd rather raise the dead than be boring.",
  "i want to be a legend that ponies tell stories about centuries from now.",
  "all i want is a simple, peaceful life with the ones i love.",
  "i feel most alive when i'm helping someone transform their life.",
  "i'm searching for my 'special talent' and fear i'll never find it.",
  "i'm happiest when every creature is being their authentic self.",
  "rules were made to be broken by great ponies.",
  "knowledge is the ultimate power.",
  "sometimes i wonder if i'm the villain of someone else's story.",
  "i believe in fate and destiny.",
  "we write our own destinies; nothing is predetermined.",
  "ancient legends and prophecies fascinate me.",
  "i would sacrifice myself without hesitation to save the world.",
  "i would sacrifice the world to save the ones i love most.",
  "immortality sounds like a nightmare.",
  "i want to explore every corner of the universe.",
  "home and family are all that really matter in the end.",
  "art, music, and beauty are what make life worth living.",
  "true strength is quiet and internal, not loud and flashy.",
  "i still carry scars (emotional or physical) from my past mistakes.",
  "i've done things i can never fully atone for.",
  "i'm a completely different person from who i was five years ago.",
  "my friends saved me from becoming a monster.",
  "i hide my true power because ponies wouldn't understand.",
  "i'm terrified my dark side will come back one day.",
  "i use humour to keep my inner demons at bay.",
  "i've found peace with who i am, flaws and all.",
  "i am exactly where i'm meant to be right now.",
  "deep down, i just want to be loved for who i really am - not what i can do.",
  "i reflect on personal growth regularly.",
  "i seek meaning in daily experiences.",
  "i question life's purpose often.",
  "i value inner peace above external success.",
  "i meditate to centre myself.",
  "i journal my thoughts.",
  "i pursue self-improvement goals.",
  "i forgive myself for past errors.",
  "i accept my limitations.",
  "i celebrate personal milestones.",
  "i adapt to life's changes.",
  "i find joy in simple pleasures.",
  "i contemplate existence deeply.",
  "i balance work and leisure.",
  "i cultivate positive habits.",
  "i let go of grudges.",
  "i embrace change as opportunity.",
  "i appreciate life's impermanence.",
  "i seek harmony in relationships.",
  "i practice gratitude daily.",
  "i explore personal beliefs.",
  "i set boundaries for wellbeing.",
  "i nurture self-compassion.",
  "i learn from setbacks.",
  "i value authenticity in self.",
  "i reflect on daily lessons.",
  "i prioritise mental health.",
  "i accept uncertainty.",
]
